export const ERROR_CODES = {
  USER_ALREADY_EXISTS: 'auth.USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'auth.USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'auth.INVALID_CREDENTIALS',
  INVALID_TOKEN: 'auth.INVALID_TOKEN',
  INTERNAL_SERVER_ERROR: 'errors.INTERNAL_SERVER_ERROR',
  INVALID_PHONE_NUMBER: 'auth.INVALID_PHONE_NUMBER',
} as const;
